//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locusnine.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblUser
    {
        [Key]
        [Required]
        [Display(Name = "ID")]
        public int id { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string name { get; set; }
        [Required]
        [Display(Name = "Email")]
        [RegularExpression(@"^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$")]
        public string email { get; set; }
        [Required]
        [Display(Name = "Role Type")]
        public string roleType { get; set; }
        [Display(Name = "Mobile Number")]
        [RegularExpression(@"[0-9]{10}")]
        public string mobileNumber { get; set; }
        [Display(Name = "Status")]
        public Nullable<int> status { get; set; }
    }
}
